/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-12-21 04:29:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberjoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/mysrc/spring/common/apache-tomcat-8.5.83-windows-x64/apache-tomcat-8.5.83/wtpwebapps/Final_project_OneTeam/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1669173602283L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>JejuDoroWE</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("   content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("   href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav\r\n");
      out.write("      class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\"\r\n");
      out.write("      id=\"ftco-navbar\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <a class=\"navbar-brand\" href=\".\">제주<span\r\n");
      out.write("            style=\"color: rgb(73, 70, 70);\">도로</span><span\r\n");
      out.write("            style=\"color: rgb(10, 183, 252);\">WE</span></a>\r\n");
      out.write("         <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("            data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\"\r\n");
      out.write("            aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("         </button>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("               <li class=\"nav-item\"><a href=\".\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("               <li class=\"nav-item\"><a href=\"reserve?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"nav-link\">예약</a></li>\r\n");
      out.write("   <!--             <li class=\"nav-item\"><a href=\"pricing\" class=\"nav-link\">기간대별</a></li> -->\r\n");
      out.write("               <li class=\"nav-item\"><a href=\"cars\" class=\"nav-link\">차종별</a></li>\r\n");
      out.write("               <li class=\"nav-item\"><a href=\"boardview\" class=\"nav-link\">Car뮤니티</a></li>\r\n");
      out.write("               <li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">고객지원</a></li>\r\n");
      out.write("               <li class=\"nav-item active\" >");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                     ");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /WEB-INF/views/member/memberjoin.jsp(71,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("                        <a href=\"");
                  out.print(request.getContextPath());
                  out.write("/myInfo?id=");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("\" class=\"nav-link\" style=\"margin-right:-30px;\">");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("님</a>\r\n");
                  out.write("                        <li class=\"nav-item active\" ><a href=\"logout\" style=\"color:#01d28e;\" class=\"nav-link\">로그아웃</a></li>\r\n");
                  out.write("                     ");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\r\n");
            out.write("                     ");
            if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("                  ");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </nav>\r\n");
      out.write("   <!-- 모달시작 -->\r\n");
      out.write("   <div class=\"modal hide\" id=\"myModal\">\r\n");
      out.write("      <form action=\"login\" method=\"POST\">\r\n");
      out.write("         <div class=\"member_login_input\">\r\n");
      out.write("            <input type=\"text\" name=\"id\" placeholder=\"아이디\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"member_login_input\">\r\n");
      out.write("            <input type=\"password\" name=\"pass\" placeholder=\"비밀번호\">\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"member_login_btn\">\r\n");
      out.write("            <input type=\"submit\" class=\"btn btn-secondary\" id=\"btn-login\"\r\n");
      out.write("               value=\"로그인\"> <input type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("               value=\"회원가입\" onclick=\"location.href='memberjoinview'\">\r\n");
      out.write("         </div>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("   <!-- 모달종료 -->\r\n");
      out.write("   <section class=\"hero-wrap hero-wrap-2 js-fullheight\"\r\n");
      out.write("      style=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/resources/images/myinfo_main.jpg');\"\r\n");
      out.write("      data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("      <div class=\"overlay\"></div>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div\r\n");
      out.write("            class=\"row no-gutters slider-text js-fullheight align-items-end justify-content-start\">\r\n");
      out.write("            <div class=\"col-md-9 ftco-animate pb-5\">\r\n");
      out.write("               <p class=\"breadcrumbs\">\r\n");
      out.write("                  <span class=\"mr-2\"><a href=\"index.html\">Home <i\r\n");
      out.write("                        class=\"ion-ios-arrow-forward\"></i></a></span> <span>회원가입 <i\r\n");
      out.write("                     class=\"ion-ios-arrow-forward\"></i></span>\r\n");
      out.write("               </p>\r\n");
      out.write("               <h1 class=\"mb-3 bread\">신규회원가입</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </section>\r\n");
      out.write("\r\n");
      out.write("   <section class=\"ftco-section contact-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"row d-flex mb-5 contact-info\">\r\n");
      out.write("            <div class=\"col-md-8 block-9 mb-md-5\">\r\n");
      out.write("               <div id=\"joinform\">\r\n");
      out.write("\r\n");
      out.write("                  <form class=\"form-group\" action=\"memberinsert\" method=\"POST\"\r\n");
      out.write("                     id=\"formMem\">\r\n");
      out.write("                     <div style=\"margin-bottom: 20px;\">\r\n");
      out.write("                        <span style=\"padding-right: 100px;\"><b>아이디</b></span> <span>\r\n");
      out.write("                           <input type=\"text\" name=\"id\" id=\"id\" value=\"\" autofocus required \r\n");
      out.write("                           pattern=\"^[A-Za-z0-9]{8,10}$\"/> <b>\r\n");
      out.write("                              *영문+숫자포함 8~10글자</b> <input type=\"text\" hidden=\"\" name=\"idChk\" id=\"idChk\" required>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <div id=\"errorId\"></div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div style=\"margin-bottom: 20px;\">\r\n");
      out.write("                        <span style=\"padding-right: 84px;\"><b>비밀번호</b></span> <span><input\r\n");
      out.write("                           type=\"password\" name=\"pass\" id=\"pass\" required \r\n");
      out.write("                           pattern=\"^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{10,12}$\"/> <b>\r\n");
      out.write("                              * 영문+숫자+특수문자1개이상 포함 10~12글자</b> </span>\r\n");
      out.write("                        <div id=\"errorPass\"></div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div style=\"margin-bottom: 20px;\">\r\n");
      out.write("                        <span style=\"padding-right: 118px;\"><b>이름</b></span> \r\n");
      out.write("                        <span>\r\n");
      out.write("                        <input type=\"text\" name=\"name\" id=\"name\" required>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <div id=\"errorName\"></div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div style=\"margin-bottom: 20px;\">\r\n");
      out.write("                        <span style=\"padding-right: 87px;\"><b>전화번호</b></span> <span><input\r\n");
      out.write("                           type=\"tel\" name=\"tel\" id=\"tel\" placeholder=\"010-0000-0000\"\r\n");
      out.write("                           required maxlength=\"13\" onkeyup=\"keyevent();\" pattern=\"[0]{1}[1]{1}[0]{1}-[0-9]{4}-[0-9]{4}\" required>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <div id=\"errorTel\"></div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div style=\"margin-bottom: 20px;\">\r\n");
      out.write("                        <span style=\"padding-right: 85px;\"><b>생년월일</b></span> <span>\r\n");
      out.write("                           <select name=\"yy\" id=\"year\"></select>년 <select name=\"mm\"\r\n");
      out.write("                           id=\"month\"></select>월 <select name=\"dd\" id=\"day\"></select>일\r\n");
      out.write("                        </span>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div style=\"margin-bottom: 20px;\">\r\n");
      out.write("                        <span style=\"padding-right: 98px;\"><b>주 소</b></span> <span\r\n");
      out.write("                           class=\"col-md-2 offset-md-0\"> <input type=\"text\"\r\n");
      out.write("                           name=\"postcode\" id=\"postcode\" placeholder=\"우편번호\" readonly />\r\n");
      out.write("                        </span> <span class=\"col-md-2 postcode-btn\">\r\n");
      out.write("                           <button type=\"button\" class=\"btn btn-info m-btn--air\"\r\n");
      out.write("                              onclick=\"execDaumPostcode()\">우편번호 찾기</button>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <div style=\"margin-left: 150px;\">\r\n");
      out.write("                           <input type=\"text\" name=\"address\" id=\"address\"\r\n");
      out.write("                              placeholder=\"도로명 주소\" style=\"width: 360px;\" readonly />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"margin-left: 150px;\">\r\n");
      out.write("                           <input type=\"text\" name=\"detailAddress\" id=\"detailAddress\"\r\n");
      out.write("                              placeholder=\"상세 주소\" style=\"width: 360px;\" required />\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div id=\"errorAddress\"></div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div style=\"margin-bottom: 20px;\">\r\n");
      out.write("                        <span style=\"padding-right: 110px;\"><b>성 별</b></span> <span>남자<input\r\n");
      out.write("                           type=\"radio\" name=\"gender\" value=\"M\" checked> 여자<input\r\n");
      out.write("                           type=\"radio\" name=\"gender\" value=\"W\"></span>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div style=\"margin-bottom: 20px;\">\r\n");
      out.write("                        <span style=\"padding-right: 100px;\"><b>이메일</b></span> <span>\r\n");
      out.write("                           <input type=\"text\" name=\"emailId\" id=\"emailId\" required/> <input\r\n");
      out.write("                           id=\"domainTxt\" type=\"text\" name=\"domainTxt\" required/> <select\r\n");
      out.write("                           class=\"box\" id=\"domain-list\">\r\n");
      out.write("                              <option value=\"type\">직접 입력</option>\r\n");
      out.write("                              <option value=\"@gmail.com\">gmail.com</option>\r\n");
      out.write("                              <option value=\"@hanmail.net\">hanmail.net</option>\r\n");
      out.write("                              <option value=\"@nate.com\">nate.com</option>\r\n");
      out.write("                              <option value=\"@kakao.com\">kakao.com</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <div id=\"errorEmail\"></div>\r\n");
      out.write("                     </div>\r\n");
      out.write("\r\n");
      out.write("                     <input type=\"submit\" value=\"가입하기\"\r\n");
      out.write("                        class=\"btn btn-primary py-3 px-5\" id=\"checkSubmit\">\r\n");
      out.write("                  </form>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("               <div id=\"map\" class=\"bg-white\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <footer class=\"ftco-footer ftco-bg-dark ftco-section\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"row mb-5\">\r\n");
      out.write("            <div class=\"col-md\">\r\n");
      out.write("               <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                  <h2 class=\"ftco-heading-2\">\r\n");
      out.write("                     <a href=\"#\" class=\"logo\">제주<span\r\n");
      out.write("                        style=\"color: rgb(190, 175, 175);\">도로</span><span\r\n");
      out.write("                        style=\"color: rgb(10, 183, 252);\">WE</span></a>\r\n");
      out.write("                  </h2>\r\n");
      out.write("                  <p>Far far away, behind the word mountains, far from the\r\n");
      out.write("                     countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("                  <ul\r\n");
      out.write("                     class=\"ftco-footer-social list-unstyled float-md-left float-lft mt-5\">\r\n");
      out.write("                     <li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("                           class=\"icon-twitter\"></span></a></li>\r\n");
      out.write("                     <li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("                           class=\"icon-facebook\"></span></a></li>\r\n");
      out.write("                     <li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("                           class=\"icon-instagram\"></span></a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md\">\r\n");
      out.write("               <div class=\"ftco-footer-widget mb-4 ml-md-5\">\r\n");
      out.write("                  <h2 class=\"ftco-heading-2\">Information</h2>\r\n");
      out.write("                  <ul class=\"list-unstyled\">\r\n");
      out.write("                     <li><a href=\"#\" class=\"py-2 d-block\">About</a></li>\r\n");
      out.write("                     <li><a href=\"#\" class=\"py-2 d-block\">Services</a></li>\r\n");
      out.write("                     <li><a href=\"#\" class=\"py-2 d-block\">Term and Conditions</a></li>\r\n");
      out.write("                     <li><a href=\"#\" class=\"py-2 d-block\">Best Price\r\n");
      out.write("                           Guarantee</a></li>\r\n");
      out.write("                     <li><a href=\"#\" class=\"py-2 d-block\">Privacy &amp;\r\n");
      out.write("                           Cookies Policy</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md\">\r\n");
      out.write("               <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                  <h2 class=\"ftco-heading-2\">Customer Support</h2>\r\n");
      out.write("                  <ul class=\"list-unstyled\">\r\n");
      out.write("                     <li><a href=\"#\" class=\"py-2 d-block\">FAQ</a></li>\r\n");
      out.write("                     <li><a href=\"#\" class=\"py-2 d-block\">Payment Option</a></li>\r\n");
      out.write("                     <li><a href=\"#\" class=\"py-2 d-block\">Booking Tips</a></li>\r\n");
      out.write("                     <li><a href=\"#\" class=\"py-2 d-block\">How it works</a></li>\r\n");
      out.write("                     <li><a href=\"#\" class=\"py-2 d-block\">Contact Us</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md\">\r\n");
      out.write("               <div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("                  <h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("                  <div class=\"block-23 mb-3\">\r\n");
      out.write("                     <ul>\r\n");
      out.write("                        <li><span class=\"icon icon-map-marker\"></span><span\r\n");
      out.write("                           class=\"text\">제주 제주시 다호5길 400 제주도로WE</span></li>\r\n");
      out.write("                        <li><a href=\"#\"><span class=\"icon icon-phone\"></span><span\r\n");
      out.write("                              class=\"text\">+81) 016-7117-972</span></a></li>\r\n");
      out.write("                        <li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span\r\n");
      out.write("                              class=\"text\">info@human.com</span></a></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("               <p>\r\n");
      out.write("                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("                  Copyright &copy;\r\n");
      out.write("                  <script>\r\n");
      out.write("                     document.write(new Date().getFullYear());\r\n");
      out.write("                  </script>\r\n");
      out.write("                  All rights reserved | This template is made with <i\r\n");
      out.write("                     class=\"icon-heart color-danger\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("                     href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("               </p>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- loader -->\r\n");
      out.write("   <div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("      <svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("         <circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("            stroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("         <circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("            stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("   <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/popper.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("   <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/aos.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyAD3NDCFvTLCdUFtWJXoV54L0a07IhAC4E&callback=initMap&region=kr\">  </script>\r\n");
      out.write("   <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/google-map.js\"></script>\r\n");
      out.write("   <script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <!--autoload=false 파라미터를 이용하여 자동으로 로딩되는 것을 막습니다.-->\r\n");
      out.write("   <script\r\n");
      out.write("      src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js?autoload=false\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   const domainListEl = document.querySelector('#domain-list')\r\n");
      out.write("   const domainInputEl = document.querySelector('#domainTxt')\r\n");
      out.write("   var pass = document.getElementById('pass');\r\n");
      out.write("   var tel = document.getElementById('tel');\r\n");
      out.write("   var id = document.getElementById('id');\r\n");
      out.write("   var idChk = document.getElementById('idChk');\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   /* 아이디 유효성 검사 및 중복 확인 */\r\n");
      out.write("   id.onkeyup = function(){   \r\n");
      out.write("      var regExpId =  /^[A-Za-z0-9]{8,10}$/; ;\r\n");
      out.write("      var idChk = document.getElementById('idChk');\r\n");
      out.write("      var errorId = document.getElementById('errorId');\r\n");
      out.write("      var testid=id.value;\r\n");
      out.write("      if(testid==\"\" ||regExpId.test(testid)==false){\r\n");
      out.write("         id.classList.add('invalid');         \r\n");
      out.write("         errorId.style=\"color:red;\"\r\n");
      out.write("         errorId.innerHTML =\"올바른 아이디 형식으로 입력하세요\";\r\n");
      out.write("      } else {\r\n");
      out.write("         this.classList.add('invalid');\r\n");
      out.write("         $.ajax({\r\n");
      out.write("            url:'");
      out.print(request.getContextPath());
      out.write("/idchk?id='+id.value,\r\n");
      out.write("            type:'GET',\r\n");
      out.write("            cache:false,   // cache옵션값을 false로 주게 되면 브라우저 캐쉬를 막아서 캐쉬된 값이 아닌 현재 값을 호출해 올 수 있다.\r\n");
      out.write("            success: function(data){\r\n");
      out.write("               if(data!=\"\"){\r\n");
      out.write("                  errorId.innerHTML = \"사용 가능한 아이디 입니다.\";\r\n");
      out.write("                  errorId.style=\"color:blue;\"\r\n");
      out.write("                  idChk.value=\"true\";\r\n");
      out.write("               } else if(data==\"\") {\r\n");
      out.write("                  errorId.style=\"color:red;\"\r\n");
      out.write("                  errorId.innerHTML = \"중복된 아이디 입니다.\";\r\n");
      out.write("               }      \r\n");
      out.write("            }, error : function(){\r\n");
      out.write("               console.log(\"-----실패-------\");\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("         });\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   /* 아이디 통과하면 비밀번호 입력할 때 아이디 유효성 알려주는 문구 사라짐 */\r\n");
      out.write("   pass.onfocus=function(){\r\n");
      out.write("      var idChk = document.getElementById('idChk');\r\n");
      out.write("      var errorId = document.getElementById('errorId');\r\n");
      out.write("      if(idChk.value==\"true\"){\r\n");
      out.write("         id.classList.remove('invalid');\r\n");
      out.write("         errorId.innerHTML =\" \";      \r\n");
      out.write("      }                     \r\n");
      out.write("   }\r\n");
      out.write("      \r\n");
      out.write("   \r\n");
      out.write("   /* 전화번호 형식 */\r\n");
      out.write("   keyevent = () => {\r\n");
      out.write("      tel.value = autoHypenPhone(tel.value);\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function autoHypenPhone(str){\r\n");
      out.write("         str = str.replace(/[^0-9]/g, '');\r\n");
      out.write("         var tmp = '';\r\n");
      out.write("         if( str.length < 4){\r\n");
      out.write("           return str;\r\n");
      out.write("         }else if(str.length < 7){\r\n");
      out.write("           tmp += str.substr(0, 3);\r\n");
      out.write("           tmp += '-';\r\n");
      out.write("           tmp += str.substr(3);\r\n");
      out.write("           return tmp;\r\n");
      out.write("         }else if(str.length < 11){\r\n");
      out.write("           tmp += str.substr(0, 3);\r\n");
      out.write("           tmp += '-';\r\n");
      out.write("           tmp += str.substr(3, 3);\r\n");
      out.write("           tmp += '-';\r\n");
      out.write("           tmp += str.substr(6);\r\n");
      out.write("           return tmp;\r\n");
      out.write("         }else{\r\n");
      out.write("           tmp += str.substr(0, 3);\r\n");
      out.write("           tmp += '-';\r\n");
      out.write("           tmp += str.substr(3, 4);\r\n");
      out.write("           tmp += '-';\r\n");
      out.write("           tmp += str.substr(7);\r\n");
      out.write("           return tmp;\r\n");
      out.write("         }\r\n");
      out.write("         return str;\r\n");
      out.write("       }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   /* 생년월일 select  */\r\n");
      out.write("   $(document).ready(function(){            \r\n");
      out.write("       var now = new Date();\r\n");
      out.write("       var year = now.getFullYear();\r\n");
      out.write("       var mon = (now.getMonth() + 1) > 9 ? ''+(now.getMonth() + 1) : '0'+(now.getMonth() + 1); \r\n");
      out.write("       var day = (now.getDate()) > 9 ? ''+(now.getDate()) : '0'+(now.getDate());           \r\n");
      out.write("       //년도 selectbox만들기               \r\n");
      out.write("       for(var i = 1920 ; i <= year ; i++) {\r\n");
      out.write("           $('#year').append('<option value=\"' + i + '\">' + i + '년</option>');    \r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       // 월별 selectbox 만들기            \r\n");
      out.write("       for(var i=1; i <= 12; i++) {\r\n");
      out.write("           var mm = i > 9 ? i : \"0\"+i ;            \r\n");
      out.write("           $('#month').append('<option value=\"' + mm + '\">' + mm + '월</option>');    \r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       // 일별 selectbox 만들기\r\n");
      out.write("       for(var i=1; i <= 31; i++) {\r\n");
      out.write("           var dd = i > 9 ? i : \"0\"+i ;            \r\n");
      out.write("           $('#day').append('<option value=\"' + dd + '\">' + dd+ '일</option>');    \r\n");
      out.write("       }\r\n");
      out.write("       $(\"#year  > option[value=\"+year+\"]\").attr(\"selected\", \"true\");        \r\n");
      out.write("       $(\"#month  > option[value=\"+mon+\"]\").attr(\"selected\", \"true\");    \r\n");
      out.write("       $(\"#day  > option[value=\"+day+\"]\").attr(\"selected\", \"true\");       \r\n");
      out.write("     \r\n");
      out.write("   })\r\n");
      out.write("   \r\n");
      out.write("   /* 주소 */\r\n");
      out.write("   \r\n");
      out.write("   /* 버튼을 클릭하여 execDaumPostcode() 함수가 호출되면서 주소 검색 팝업창이 보여지게 합니다.\r\n");
      out.write("        팝업창에서 주소 검색 결과 항목을 클릭했을 때 우편번호와 도로명주소 입력란에 값을 채워넣게 됩니다. */\r\n");
      out.write("   \r\n");
      out.write("   function execDaumPostcode() {\r\n");
      out.write("       daum.postcode.load(function(){\r\n");
      out.write("           new daum.Postcode({\r\n");
      out.write("               oncomplete: function(data) {\r\n");
      out.write("                 // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분입니다.\r\n");
      out.write("                 $(\"#postcode\").val(data.zonecode);\r\n");
      out.write("                $(\"#address\").val(data.roadAddress);\r\n");
      out.write("               }\r\n");
      out.write("           }).open();\r\n");
      out.write("       });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   // 이메일 - select 옵션 변경 시\r\n");
      out.write("   domainListEl.addEventListener('change', (event) => {\r\n");
      out.write("     // option에 있는 도메인 선택 시\r\n");
      out.write("     if(event.target.value !== \"type\") {\r\n");
      out.write("       // 선택한 도메인을 input에 입력하고 disabled\r\n");
      out.write("       domainInputEl.value = event.target.value\r\n");
      out.write("       //domainInputEl.disabled = true\r\n");
      out.write("     } else { // 직접 입력 시\r\n");
      out.write("       // input 내용 초기화 & 입력 가능하도록 변경\r\n");
      out.write("       domainInputEl.value = \"\"\r\n");
      out.write("       //domainInputEl.disabled = false\r\n");
      out.write("     }\r\n");
      out.write("   })\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        <a data-toggle=\"modal\" href=\"#myModal\" class=\"nav-link\">로그인</a>\r\n");
          out.write("                     ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
