/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-12-21 08:19:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.groupone.vo.BoardVO;
import com.groupone.vo.CommentsVO;
import java.util.*;

public final class boardone_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/mysrc/spring/common/apache-tomcat-8.5.83-windows-x64/apache-tomcat-8.5.83/wtpwebapps/Final_project_OneTeam/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1669173602283L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.groupone.vo.BoardVO");
    _jspx_imports_classes.add("com.groupone.vo.CommentsVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>JejuDoroWE</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=DM+Sans:300,400,700&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/fonts/flaticon/font/flaticon.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".bbody {\r\n");
      out.write("	margin-left: 100px;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#good, #boardMD {\r\n");
      out.write("	margin-left: 900px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	color: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".maindiv {\r\n");
      out.write("	border: 1px solid #bcbcbc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jb-table {\r\n");
      out.write("	display: table;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border: 1px solid #bcbcbc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jb-table-row {\r\n");
      out.write("	display: table-row;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jb-table-cell {\r\n");
      out.write("	display: table-cell;\r\n");
      out.write("	padding: 15px 20px;\r\n");
      out.write("	height: 70px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jb-top {\r\n");
      out.write("	vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jb-middle {\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".jb-bottom {\r\n");
      out.write("	vertical-align: bottom;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn.btn-ss {\r\n");
      out.write("    background: rgb(235, 159, 206) !important;\r\n");
      out.write("    border: 1px solid rgb(235, 159, 206) !important;\r\n");
      out.write("    color: #fff !important; }\r\n");
      out.write("    .btn.btn-secondary:hover {\r\n");
      out.write("      border: 1px solid #01d28e;\r\n");
      out.write("      background: transparent;\r\n");
      out.write("      color: #01d28e; }\r\n");
      out.write("    .btn.btn-secondary.btn-outline-secondary {\r\n");
      out.write("      border: 1px solid #01d28e;\r\n");
      out.write("      background: transparent;\r\n");
      out.write("      color: #01d28e; }\r\n");
      out.write("      .btn.btn-secondary.btn-outline-secondary:hover {\r\n");
      out.write("        border: 1px solid transparent;\r\n");
      out.write("        background: #01d28e;\r\n");
      out.write("        color: #fff; }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<body data-spy=\"scroll\" data-target=\".site-navbar-target\"\r\n");
      out.write("	data-offset=\"300\">\r\n");
      out.write("	<nav\r\n");
      out.write("		class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\"\r\n");
      out.write("		id=\"ftco-navbar\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\".\">제주<span\r\n");
      out.write("				style=\"color: rgb(190, 175, 175);\">도로</span><span\r\n");
      out.write("				style=\"color: rgb(10, 183, 252);\">WE</span></a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("				data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\"\r\n");
      out.write("				aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("				<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("					<li class=\"nav-item\"><a href=\".\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"reserve?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("						class=\"nav-link\">예약</a></li>\r\n");
      out.write("					<!-- 				<li class=\"nav-item\"><a href=\"pricing\" class=\"nav-link\">기간대별</a></li> -->\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"cars\" class=\"nav-link\">차종별</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"boardview\" class=\"nav-link\">Car뮤니티</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">고객지원</a></li>\r\n");
      out.write("					<li class=\"nav-item active\">");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /WEB-INF/views/board/boardone.jsp(206,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("								<a href=\"");
                  out.print(request.getContextPath());
                  out.write("/myInfo?id=");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("\"\r\n");
                  out.write("									class=\"nav-link\" style=\"margin-right: -30px;\">");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("님</a>\r\n");
                  out.write("								<li class=\"nav-item active\"><a href=\"logout\"\r\n");
                  out.write("									style=\"color: #01d28e;\" class=\"nav-link\">로그아웃</a></li>\r\n");
                  out.write("							");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\r\n");
            out.write("							");
            if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- 모달시작 -->\r\n");
      out.write("	<div class=\"modal hide\" id=\"myModal\">\r\n");
      out.write("		<form action=\"login\" method=\"POST\"\r\n");
      out.write("			style=\"margin-top: 220px; margin-left: 550px; width: 204px;\">\r\n");
      out.write("			<div class=\"member_login_input\">\r\n");
      out.write("				<input type=\"text\" name=\"id\" placeholder=\"아이디\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"member_login_input\">\r\n");
      out.write("				<input type=\"password\" name=\"pass\" placeholder=\"비밀번호\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"member_login_btn\">\r\n");
      out.write("				<input type=\"submit\" class=\"btn btn-secondary\" id=\"btn-login\"\r\n");
      out.write("					value=\"로그인\"> <input type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("					value=\"회원가입\" onclick=\"location.href='memberjoinview'\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 모달종료 -->\r\n");
      out.write("	<section class=\"hero-wrap hero-wrap-2 js-fullheight\"\r\n");
      out.write("		style=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/resources/images/board_main.jpg');\"\r\n");
      out.write("		data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("		<div class=\"overlay\"></div>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"row no-gutters slider-text js-fullheight align-items-end justify-content-start\">\r\n");
      out.write("				<div class=\"col-md-9 ftco-animate pb-5\">\r\n");
      out.write("					<p class=\"breadcrumbs\">\r\n");
      out.write("						<span class=\"mr-2\"><a href=\"index.html\">Home <i\r\n");
      out.write("								class=\"ion-ios-arrow-forward\"></i></a></span> <span>Services <i\r\n");
      out.write("							class=\"ion-ios-arrow-forward\"></i></span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<h1 class=\"mb-3 bread\">이용후기</h1>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<hr>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"ftco-blocks-cover-1\">\r\n");
      out.write("		<div class=\"ftco-cover-1 overlay innerpage\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row align-items-center justify-content-center\">\r\n");
      out.write("					<div class=\"col-lg-6 text-center\">\r\n");
      out.write("						<h1>제주도로WE 이용후기</h1>\r\n");
      out.write("						<p>실 이용객들의 생생한 탑승후기</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<section class=\"bbody\">\r\n");
      out.write("		<div class=\"maindiv\">\r\n");
      out.write("			<div class=\"jb-table\">\r\n");
      out.write("				<div class=\"jb-table-row\">\r\n");
      out.write("					<div class=\"jb-table-cell\">\r\n");
      out.write("						<span style=\"display: inline-block; width: 60px;\"><b>\r\n");
      out.write("								글번호 </b></span> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"jb-table-cell\">\r\n");
      out.write("						<span style=\"display: inline-block; width: 60px;\"><b>\r\n");
      out.write("								제목 </b></span> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"jb-table-cell\">\r\n");
      out.write("						<span style=\"display: inline-block; width: 60px;\"><b>\r\n");
      out.write("								작성자 </b></span> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"jb-table-row\">\r\n");
      out.write("					<div class=\"jb-table-cell\">\r\n");
      out.write("						<span style=\"display: inline-block; width: 60px;\"><b>\r\n");
      out.write("								조회수 </b></span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.cnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("					<div class=\"jb-table-cell \">\r\n");
      out.write("						<span style=\"display: inline-block; width: 60px;\"><b>게시일\r\n");
      out.write("						</b></span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.bindate.substring(0,4) }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('년');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.bindate.substring(5,7)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("월\r\n");
      out.write("										");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.bindate.substring(8,10)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("일\r\n");
      out.write("										");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.bindate.substring(11,13)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('시');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.bindate.substring(14,16)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("분</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"jb-table-cell \">\r\n");
      out.write("						<span style=\"display: inline-block; width: 60px;\"><b>모델명\r\n");
      out.write("						</b></span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${carName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>\r\n");
      out.write("				<b>내용 </b>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("			\r\n");
      out.write("			<div id=\"boardMD\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("			<div id='good'>\r\n");
      out.write("				<a class=\"text-dark heart\" style=\"text-decoration-line: none;\">\r\n");
      out.write("					<input type=\"hidden\" id=\"chkL\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${heartval}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<button onclick=\"updateL()\" class=\"btn btn-ss py-2 px-4\">\r\n");
      out.write("						<img id=\"heart\"\r\n");
      out.write("							src=\"");
      out.print(request.getContextPath());
      out.write("/resources/icon/suit-heart-fill.svg\">\r\n");
      out.write("						좋아요 <span id=\"gnum\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.good}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<hr>\r\n");
      out.write("\r\n");
      out.write("			<!-- 댓글 출력부분  -->\r\n");
      out.write("			<div>\r\n");
      out.write("\r\n");
      out.write("				<div>\r\n");
      out.write("					<b>댓글</b>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<hr>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div>\r\n");
      out.write("\r\n");
      out.write("				<div>\r\n");
      out.write("					<b>댓글 작성</b>\r\n");
      out.write("				</div>\r\n");
      out.write("				<form id=\"com\" action=\"comAction\">\r\n");
      out.write("\r\n");
      out.write("					<input type=\"hidden\" name='id' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'> <input\r\n");
      out.write("						type=\"hidden\" name='bno' value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'>\r\n");
      out.write("\r\n");
      out.write("					<textarea cols=\"80\" rows=\"8\" id=\"comments\" name=\"comments\"\r\n");
      out.write("						placeholder=\"50자 이내로 입력해주세요.\"></textarea>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<input type=\"button\" value=\"등록\" onclick=\"chkCon()\" class=\"btn btn-primary btn-lg\">\r\n");
      out.write("\r\n");
      out.write("				</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<footer class=\"ftco-footer ftco-bg-dark ftco-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row mb-5\">\r\n");
      out.write("				<div class=\"col-md\">\r\n");
      out.write("					<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("						<h2 class=\"ftco-heading-2\">\r\n");
      out.write("							<a href=\"#\" class=\"logo\">제주<span\r\n");
      out.write("								style=\"color: rgb(190, 175, 175);\">도로</span><span\r\n");
      out.write("								style=\"color: rgb(10, 183, 252);\">WE</span></a>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<p>Far far away, behind the word mountains, far from the\r\n");
      out.write("							countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("						<ul\r\n");
      out.write("							class=\"ftco-footer-social list-unstyled float-md-left float-lft mt-5\">\r\n");
      out.write("							<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("									class=\"icon-twitter\"></span></a></li>\r\n");
      out.write("							<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("									class=\"icon-facebook\"></span></a></li>\r\n");
      out.write("							<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("									class=\"icon-instagram\"></span></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md\">\r\n");
      out.write("					<div class=\"ftco-footer-widget mb-4 ml-md-5\">\r\n");
      out.write("						<h2 class=\"ftco-heading-2\">Information</h2>\r\n");
      out.write("						<ul class=\"list-unstyled\">\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">About</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Services</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Term and Conditions</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Best Price\r\n");
      out.write("									Guarantee</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Privacy &amp;\r\n");
      out.write("									Cookies Policy</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md\">\r\n");
      out.write("					<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("						<h2 class=\"ftco-heading-2\">Customer Support</h2>\r\n");
      out.write("						<ul class=\"list-unstyled\">\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">FAQ</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Payment Option</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Booking Tips</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">How it works</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Contact Us</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md\">\r\n");
      out.write("					<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("						<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("						<div class=\"block-23 mb-3\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><span class=\"icon icon-map-marker\"></span><span\r\n");
      out.write("									class=\"text\">제주 제주시 다호5길 400 제주도로WE</span></li>\r\n");
      out.write("								<li><a href=\"#\"><span class=\"icon icon-phone\"></span><span\r\n");
      out.write("										class=\"text\">+81) 016-7117-972</span></a></li>\r\n");
      out.write("								<li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span\r\n");
      out.write("										class=\"text\">info@human.com</span></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("					<p>\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("						Copyright &copy;\r\n");
      out.write("						<script>\r\n");
      out.write("							document.write(new Date().getFullYear());\r\n");
      out.write("						</script>\r\n");
      out.write("						All rights reserved | This template is made with <i\r\n");
      out.write("							class=\"icon-heart color-danger\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("							href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<script>	      \r\n");
      out.write("		function cmUpdateOpen(bbno) {      \r\n");
      out.write("        var modiF = document.getElementById('modiComment'+bbno); //div id 댓글별로 서로다른 div가 있어야 하기때문에 div id에 기본키인 댓글 번호를 붙여주어 구분함\r\n");
      out.write("        var modiC = document.getElementById(bbno+'C').innerHTML; // span의 value값 꺼내오기\r\n");
      out.write("        var modiOK = document.getElementById(bbno+'C');\r\n");
      out.write("        \r\n");
      out.write("        modiF.innerHTML=\"<input type='text'style='width:500px;'  maxlength='50' id='modText\"+bbno+\"' value='\"+modiC.trim()+\"'>\";\r\n");
      out.write("        modiF.innerHTML+=\"<button id='modiBtn' >수정</button>\";\r\n");
      out.write("        modiF.innerHTML   +=\"<button id='backBtn' onclick='back()' >취소</button>\";\r\n");
      out.write("        let msg = \"수정하시겠습니까?\";\r\n");
      out.write("        if(confirm(msg)!=0){ \r\n");
      out.write("           var modText=document.getElementById('modText'+bbno).value;\r\n");
      out.write("\r\n");
      out.write("           $('html').click(function(e) {   \r\n");
      out.write("              //내가 클릭한 부분이 수정할 댓글 범위의 div를 넘어가면 수정내용을 입력하는 텍스트 필드가 사라진다.\r\n");
      out.write("              var b= e.target;\r\n");
      out.write("              //b=b.parentNode;\r\n");
      out.write("              var a=document.querySelector('.modiC'+bbno);\r\n");
      out.write("              console.log(a);\r\n");
      out.write("              var c = 0;\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              while(b!=null){ //b의 최상위 nord까지 while문이 돌아감\r\n");
      out.write("                 b=b.parentNode; \r\n");
      out.write("                 console.log(b);   \r\n");
      out.write("                  if(a==b) {\r\n");
      out.write("                    c=1;\r\n");
      out.write("                     break;         \r\n");
      out.write("                 } \r\n");
      out.write("              }\r\n");
      out.write("              \r\n");
      out.write("              if(c==0){\r\n");
      out.write("                 console.log('modiC'+bbno);\r\n");
      out.write("                 modiF.innerHTML=\"\";\r\n");
      out.write("              }\r\n");
      out.write("              \r\n");
      out.write("           });   \r\n");
      out.write("           \r\n");
      out.write("           back=()=>{\r\n");
      out.write("              modiF.innerHTML=\"\";\r\n");
      out.write("           }\r\n");
      out.write("           \r\n");
      out.write("           $(document).on('click', '#modiBtn', function(e) {\r\n");
      out.write("                    modText=document.getElementById('modText'+bbno).value;\r\n");
      out.write("                    console.log(modText);\r\n");
      out.write("                       $.ajax({\r\n");
      out.write("                          \r\n");
      out.write("                          type: 'GET',\r\n");
      out.write("                          url: './modicom?bbno='+bbno+'&comments='+modText,\r\n");
      out.write("                       \r\n");
      out.write("                          cache:false,\r\n");
      out.write("                          success: function(data) {\r\n");
      out.write("                             modiOK.innerHTML=modText;\r\n");
      out.write("                             modiF.innerHTML=\"\";\r\n");
      out.write("                             console.log(\"DB상 수정 완료\");\r\n");
      out.write("                          },error : function(){\r\n");
      out.write("                             console.log(\"-----실패-------\");\r\n");
      out.write("                          }\r\n");
      out.write("                          \r\n");
      out.write("                       }) \r\n");
      out.write("                    \r\n");
      out.write("           \r\n");
      out.write("                 });   \r\n");
      out.write("        } else {  // 취소버튼 누르면 없어짐\r\n");
      out.write("           modiF.innerHTML=\"\";\r\n");
      out.write("           \r\n");
      out.write("        }\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		//댓글 수정 삭제\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function () {\r\n");
      out.write("				\r\n");
      out.write("	// 좋아요가 있는지 확인한 값을 heartval에 저장\r\n");
      out.write("        var heartval = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${heartval}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("        // heartval이 1이면 좋아요가 이미 되있는것이므로 heart-fill.svg를 출력하는 코드\r\n");
      out.write("        if(heartval>0) {\r\n");
      out.write("            console.log(heartval);\r\n");
      out.write("            $(\"#heart\").prop(\"src\", \"");
      out.print(request.getContextPath());
      out.write("/resources/icon/suit-heart-fill.svg\");\r\n");
      out.write("           \r\n");
      out.write("        }\r\n");
      out.write("        else {\r\n");
      out.write("            console.log(heartval);\r\n");
      out.write("            $(\"#heart\").prop(\"src\", \"");
      out.print(request.getContextPath());
      out.write("/resources/icon/suit-heart.svg\");\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	// 좋아요 버튼을 클릭 시 실행되는 코드\r\n");
      out.write(" 		updateL=()=>{\r\n");
      out.write(" 			var heartval = document.getElementById('chkL');\r\n");
      out.write(" 			var gnumval = Number(document.getElementById('gnum').innerHTML);\r\n");
      out.write(" 			var gnum = document.getElementById('gnum');\r\n");
      out.write(" 			// 총 좋아요 갯수를 숫자로 변환\r\n");
      out.write(" 			\r\n");
      out.write(" 			\r\n");
      out.write(" 	        if(heartval.value>0) {\r\n");
      out.write(" 	            console.log(heartval);\r\n");
      out.write(" 	           $(\"#heart\").prop(\"src\", \"");
      out.print(request.getContextPath());
      out.write("/resources/icon/suit-heart.svg\");	            \r\n");
      out.write(" 	           \r\n");
      out.write(" 	        }else {\r\n");
      out.write(" 	            console.log(heartval);\r\n");
      out.write(" 	           $(\"#heart\").prop(\"src\", \"");
      out.print(request.getContextPath());
      out.write("/resources/icon/suit-heart-fill.svg\"); \r\n");
      out.write(" 	        }\r\n");
      out.write(" 			\r\n");
      out.write(" 			\r\n");
      out.write(" 			\r\n");
      out.write("  			$.ajax({\r\n");
      out.write("				type: 'GET',\r\n");
      out.write("				url: './updateG',\r\n");
      out.write("				data : {'heartval': heartval.value, 'id':'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', 'bno':");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("},\r\n");
      out.write("				cache:false,\r\n");
      out.write("				success: function(data) {\r\n");
      out.write("					if(heartval.value>0) {\r\n");
      out.write("						console.log(heartval);\r\n");
      out.write("						heartval.value=0;\r\n");
      out.write("						gnum.innerHTML=gnumval-1;\r\n");
      out.write("						console.log(\"0??????\")\r\n");
      out.write("		 	        }else {\r\n");
      out.write("		 	        	heartval.value=1;\r\n");
      out.write("		 	        	console.log(\"1??????\")\r\n");
      out.write("		 	        	gnum.innerHTML=gnumval+1;\r\n");
      out.write("		 	        }\r\n");
      out.write("					console.log(\"DB상 수정 완료\");\r\n");
      out.write("				},error : function(){\r\n");
      out.write("					console.log(\"-----실패-------\");\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write(" 				\r\n");
      out.write(" 		}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("		delC=(cbno,bno)=>{				\r\n");
      out.write("	        let msg = \"삭제하시겠습니까?\";\r\n");
      out.write("	        if (confirm(msg)!=0) {\r\n");
      out.write("	        	location.href='delCom?bbno='+cbno+'&bno='+bno+'&id='+'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("	        } else {\r\n");
      out.write("	            // no click\r\n");
      out.write("	        }    \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		// 게시글 수정 삭제\r\n");
      out.write("		delB=(bno)=>{\r\n");
      out.write("	        let msg = \"삭제하시겠습니까?\";\r\n");
      out.write("	        if (confirm(msg)!=0) {\r\n");
      out.write("	        	location.href='delBoard?bno='+bno;\r\n");
      out.write("	        } else {\r\n");
      out.write("	            // no click\r\n");
      out.write("	        }    \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		modiB=(bno)=>{\r\n");
      out.write("	        let msg = \"수정하시겠습니까?\";\r\n");
      out.write("	        if (confirm(msg)!=0) {\r\n");
      out.write("	        	location.href='modiBoard?bno='+bno;\r\n");
      out.write("	        } else {\r\n");
      out.write("	            // no click\r\n");
      out.write("	        }    \r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		chkCon=()=>{ //댓글의 내용이 입력되었는지 확인 후 댓글 등록\r\n");
      out.write("			let comments=document.getElementById('comments');\r\n");
      out.write("			console.log(comments);\r\n");
      out.write("			\r\n");
      out.write("			if(comments.value==\"\"){\r\n");
      out.write("				alert('내용을 입력해주세요')\r\n");
      out.write("			}else if(comments.value.length>=50){\r\n");
      out.write("				alert('50글자 이하로 입력해주세요')\r\n");
      out.write("			}else{\r\n");
      out.write("				document.getElementById('com').submit();\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	   </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- loader -->\r\n");
      out.write("	<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("		<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				stroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/aos.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/google-map.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<a data-toggle=\"modal\" href=\"#myModal\" class=\"nav-link\">로그인</a>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/board/boardone.jsp(312,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("fname");
      // /WEB-INF/views/board/boardone.jsp(312,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/boardone.jsp(312,4) '${bvo.fname}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${bvo.fname}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/board/boardone.jsp(312,4) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("session");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/board/boardone.jsp(315,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fname == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<img src=\"download?filename=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.fname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" width='250px' height='250px'>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/board/boardone.jsp(329,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("lid");
      // /WEB-INF/views/board/boardone.jsp(329,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/boardone.jsp(329,4) '${login_id}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${login_id}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/board/boardone.jsp(330,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("id");
      // /WEB-INF/views/board/boardone.jsp(330,4) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/boardone.jsp(330,4) '${bvo.id}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${bvo.id}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/board/boardone.jsp(331,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id eq lid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<td><input type=\"button\" value=\"수정\"\r\n");
          out.write("						onclick=\"modiB(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\" class=\"btn btn-primary btn-lg\"> <input type=\"button\"\r\n");
          out.write("						value=\"삭제\" onclick=\"delB(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\" class=\"btn btn-primary btn-lg\"></td>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/board/boardone.jsp(361,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/boardone.jsp(361,4) '${clist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${clist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/board/boardone.jsp(361,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("cvo");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<div class=\"modiC");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.bbno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("						<div>\r\n");
            out.write("							<span style=\"display: inline-block; width: 100px;\">\r\n");
            out.write("								");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span> <span id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.bbno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("C\"\r\n");
            out.write("								style=\"display: inline-block; width: 500px;\">\r\n");
            out.write("								");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.comments}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span> <span\r\n");
            out.write("								style=\"display: inline-block; width: 200px;\">\r\n");
            out.write("								");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.bbindate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" </span>\r\n");
            out.write("							");
            if (_jspx_meth_c_005fset_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("							");
            if (_jspx_meth_c_005fset_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("							");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("						</div>\r\n");
            out.write("					</div>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/board/boardone.jsp(370,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setVar("lid");
      // /WEB-INF/views/board/boardone.jsp(370,7) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/boardone.jsp(370,7) '${login_id}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${login_id}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f4_reused = false;
    try {
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/board/boardone.jsp(371,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setVar("id");
      // /WEB-INF/views/board/boardone.jsp(371,7) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/boardone.jsp(371,7) '${cvo.id}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cvo.id}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      _jspx_th_c_005fset_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/board/boardone.jsp(372,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id eq lid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("								<a style=\"color: blue\" id=\"m");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.bbno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("									onclick=\"cmUpdateOpen(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.bbno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">수정</a>\r\n");
          out.write("								<a style=\"color: blue\" onclick=\"delC(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.bbno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(',');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bvo.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">삭제</a>\r\n");
          out.write("\r\n");
          out.write("								<div id=\"modiComment");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.bbno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></div>\r\n");
          out.write("\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
