/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2022-12-19 08:25:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reserve;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reserve_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/mysrc/spring/common/apache-tomcat-8.5.83-windows-x64/apache-tomcat-8.5.83/wtpwebapps/Final_project_OneTeam/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1669173602283L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>JejuDoroWE</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/open-iconic-bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/animate.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/magnific-popup.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/aos.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/ionicons.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/bootstrap-datepicker.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/jquery.timepicker.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/flaticon.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/icomoon.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav\r\n");
      out.write("		class=\"navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light\"\r\n");
      out.write("		id=\"ftco-navbar\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<a class=\"navbar-brand\" href=\".\">제주<span\r\n");
      out.write("				style=\"color: rgb(73, 70, 70);\">도로</span><span\r\n");
      out.write("				style=\"color: rgb(10, 183, 252);\">WE</span></a>\r\n");
      out.write("			<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("				data-target=\"#ftco-nav\" aria-controls=\"ftco-nav\"\r\n");
      out.write("				aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("				<span class=\"oi oi-menu\"></span> Menu\r\n");
      out.write("			</button>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"collapse navbar-collapse\" id=\"ftco-nav\">\r\n");
      out.write("				<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("					<li class=\"nav-item\"><a href=\".\" class=\"nav-link\">Home</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"reserve?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("						class=\"nav-link\">예약</a></li>\r\n");
      out.write("					<!-- 				<li class=\"nav-item\"><a href=\"pricing\" class=\"nav-link\">기간대별</a></li> -->\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"cars\" class=\"nav-link\">차종별</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"boardview\" class=\"nav-link\">Car뮤니티</a></li>\r\n");
      out.write("					<li class=\"nav-item\"><a href=\"#\" class=\"nav-link\">고객지원</a></li>\r\n");
      out.write("					<li class=\"nav-item active\">");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /WEB-INF/views/reserve/reserve.jsp(73,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("								<a href=\"");
                  out.print(request.getContextPath());
                  out.write("/myInfo?id=");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("\"\r\n");
                  out.write("									class=\"nav-link\" style=\"margin-right: -30px;\">");
                  out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
                  out.write("님</a>\r\n");
                  out.write("								<li class=\"nav-item active\"><a href=\"logout\"\r\n");
                  out.write("									style=\"color: #01d28e;\" class=\"nav-link\">로그아웃</a></li>\r\n");
                  out.write("							");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\r\n");
            out.write("							");
            if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write("\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- 모달시작 -->\r\n");
      out.write("	<div class=\"modal hide\" id=\"myModal\">\r\n");
      out.write("		<form action=\"login\" method=\"POST\"\r\n");
      out.write("			style=\"margin-top: 220px; margin-left: 550px; width: 204px;\">\r\n");
      out.write("			<div class=\"member_login_input\">\r\n");
      out.write("				<input type=\"text\" name=\"id\" placeholder=\"아이디\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"member_login_input\">\r\n");
      out.write("				<input type=\"password\" name=\"pass\" placeholder=\"비밀번호\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"member_login_btn\">\r\n");
      out.write("				<input type=\"submit\" class=\"btn btn-secondary\" id=\"btn-login\"\r\n");
      out.write("					value=\"로그인\"> <input type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("					value=\"회원가입\" onclick=\"location.href='memberjoinview'\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 모달종료 -->\r\n");
      out.write("	<!-- END nav -->\r\n");
      out.write("\r\n");
      out.write("	<section class=\"hero-wrap hero-wrap-2 js-fullheight\"\r\n");
      out.write("		style=\"background-image: url('");
      out.print(request.getContextPath());
      out.write("/resources/images/reservemain.png');\"\r\n");
      out.write("		data-stellar-background-ratio=\"0.5\">\r\n");
      out.write("		<div class=\"overlay\"></div>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"row no-gutters slider-text js-fullheight align-items-end justify-content-start\">\r\n");
      out.write("				<div class=\"col-md-9 ftco-animate pb-5\">\r\n");
      out.write("					<p class=\"breadcrumbs\">\r\n");
      out.write("						<span class=\"mr-2\"><a href=\"index.html\">Home <i\r\n");
      out.write("								class=\"ion-ios-arrow-forward\"></i></a></span> <span>예약하기 <i\r\n");
      out.write("							class=\"ion-ios-arrow-forward\"></i></span>\r\n");
      out.write("					</p>\r\n");
      out.write("					<h1 class=\"mb-3 bread\">렌트 예약</h1>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"ftco-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row d-flex mb-5 contact-info\">\r\n");
      out.write("				<div class=\"col-md-8 block-9 mb-md-5\">\r\n");
      out.write("					<div id=\"joinform\">\r\n");
      out.write("						<form class=\"form-group\" action=\"reserveinsert\" method=\"get\">\r\n");
      out.write("							<div class=\"elem-group form\">\r\n");
      out.write("								<label for=\"name\">아이디</label> <input type=\"text\" id=\"id\"\r\n");
      out.write("									name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"elem-group inlined\">\r\n");
      out.write("								<label for=\"cartype\">차량선택</label> <select onchange=\"car(this)\"\r\n");
      out.write("									class=\"form-control\" name=\"cartype\" required id=\"cartype\">\r\n");
      out.write("									<option value=\"\">차량선택</option>\r\n");
      out.write("									<option value=\"경차\">경차</option>\r\n");
      out.write("									<option value=\"소형차\">소형차</option>\r\n");
      out.write("									<option value=\"중형차\">중형차</option>\r\n");
      out.write("									<option value=\"준대형차\">준대형차</option>\r\n");
      out.write("									<option value=\"대형차\">대형차</option>\r\n");
      out.write("									<option value=\"승합차\">승합차</option>\r\n");
      out.write("									<option value=\"SUV\">SUV</option>\r\n");
      out.write("									<option value=\"전기차\">전기차</option>\r\n");
      out.write("									");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"elem-group inlined\">\r\n");
      out.write("								<label for=\"\">차량 모델</label> <label for=\"\" class=\"label\">차량\r\n");
      out.write("									모델</label> <select id=\"carlist\" class=\"form-control\" name=\"carname\"\r\n");
      out.write("									required>\r\n");
      out.write("									<option value=\"\">차량모델을 선택해주세요</option>\r\n");
      out.write("									");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("							<hr>\r\n");
      out.write("							<div class=\"elem-group inlined\">\r\n");
      out.write("								<label for=\"\">면허 종류</label> <input type=\"number\"\r\n");
      out.write("									id=\"licensetype\" name=\"licensetype\" value=\"2\" min=\"1\" max=\"2\"\r\n");
      out.write("									required>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"elem-group inlined\">\r\n");
      out.write("								<label for=\"\">면허번호</label> <input type=\"text\" id=\"licensenum\"\r\n");
      out.write("									pattern=\"[0-9]{2}-[0-9]{2}-[0-9]{6}-[0-9]{2}\" name=\"licensenum\"\r\n");
      out.write("									placeholder=\"AA-BB-CCCCCC-DE\" maxlength=\"15\" required\r\n");
      out.write("									onkeyup=\"keyevent();\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"elem-group inlined\">\r\n");
      out.write("								<label for=\"rentdate\">대여일</label> <input type=\"date\"\r\n");
      out.write("									class=\"form-control\" id=\"rentdate\" name=\"rentdate\" required\r\n");
      out.write("									value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rvo.getRentdate() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"elem-group inlined\">\r\n");
      out.write("								<label for=\"\" class=\"label\">픽업 시간</label> <select\r\n");
      out.write("									name=\"time_pick\" class=\"form-control\">\r\n");
      out.write("									<option value=\"11\">오전 11시</option>\r\n");
      out.write("									<option value=\"12\">오후 12시</option>\r\n");
      out.write("									<option value=\"13\">오후 1시</option>\r\n");
      out.write("									<option value=\"14\">오후 2시</option>\r\n");
      out.write("									<option value=\"15\">오후 3시</option>\r\n");
      out.write("									<option value=\"16\">오후 4시</option>\r\n");
      out.write("									<option value=\"17\">오후 5시</option>\r\n");
      out.write("									<option value=\"18\">오후 6시</option>\r\n");
      out.write("									<option value=\"19\">오후 7시</option>\r\n");
      out.write("									<option value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time_pick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" selected hidden=\"\">\r\n");
      out.write("										");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("										");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("										");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("									</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"elem-group inlined\">\r\n");
      out.write("\r\n");
      out.write("								<label for=\"\" class=\"label\">반납일</label> <input type=\"date\"\r\n");
      out.write("									class=\"form-control\" id=\"returndate\" placeholder=\"Date\"\r\n");
      out.write("									name=\"returndate\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rvo.getReturndate() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"elem-group inlined \">\r\n");
      out.write("								<label for=\"coupon\">쿠폰선택</label> <select class=\"form-control\"\r\n");
      out.write("									name=\"coupon\" id=\"coupon\" onchange=\"cal()\">\r\n");
      out.write("\r\n");
      out.write("									<option value=\"\" >쿠폰선택</option>\r\n");
      out.write("									");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"elem-group\">\r\n");
      out.write("								<label for=\"insurance\"\r\n");
      out.write("									style=\"margin-right: 100px; margin-top: 50px;\">보험여부</label> 네<input\r\n");
      out.write("									type=\"radio\" name=\"insurance\" value=\"Y\" required\r\n");
      out.write("									style=\"margin-right: 100px;\" onchange=\"cal()\"> 아니오<input type=\"radio\"\r\n");
      out.write("									name=\"insurance\" value=\"N\" onclick=\"cal()\" checked>\r\n");
      out.write("									<span id=\"sumpay\" style=\"color:green; margin-left:100px;\">\r\n");
      out.write("									</span>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<hr>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"elem-group\" style=\"margin-top: 50px\">\r\n");
      out.write("								<label for=\"message\">요구사항</label> <br>\r\n");
      out.write("								<textarea id=\"require\" name=\"require\" rows=\"5\" cols=\"50\"\r\n");
      out.write("									placeholder=\"특이사항을 입력해주세요\" required></textarea>\r\n");
      out.write("							</div>\r\n");
      out.write("							<input type=\"submit\" value=\"예약하기\"\r\n");
      out.write("								class=\"btn btn-primary py-3 px-5\">\r\n");
      out.write("\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<section class=\"ftco-section ftco-intro\"\r\n");
      out.write("		style=\"background-image: url(");
      out.print(request.getContextPath());
      out.write("/resources/images/bg_3.jpg);\">\r\n");
      out.write("		<div class=\"overlay\"></div>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-end\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"col-md-6 heading-section heading-section-white ftco-animate\">\r\n");
      out.write("					<h2 class=\"mb-3\">Do You Want To Earn With Us? So Don't Be\r\n");
      out.write("						Late.</h2>\r\n");
      out.write("					<a href=\"#\" class=\"btn btn-primary btn-lg\">Become A Driver</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<footer class=\"ftco-footer ftco-bg-dark ftco-section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row mb-5\">\r\n");
      out.write("				<div class=\"col-md\">\r\n");
      out.write("					<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("						<h2 class=\"ftco-heading-2\">\r\n");
      out.write("							<a href=\"#\" class=\"logo\">제주<span\r\n");
      out.write("								style=\"color: rgb(190, 175, 175);\">도로</span><span\r\n");
      out.write("								style=\"color: rgb(10, 183, 252);\">WE</span></a>\r\n");
      out.write("						</h2>\r\n");
      out.write("						<p>Far far away, behind the word mountains, far from the\r\n");
      out.write("							countries Vokalia and Consonantia, there live the blind texts.</p>\r\n");
      out.write("						<ul\r\n");
      out.write("							class=\"ftco-footer-social list-unstyled float-md-left float-lft mt-5\">\r\n");
      out.write("							<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("									class=\"icon-twitter\"></span></a></li>\r\n");
      out.write("							<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("									class=\"icon-facebook\"></span></a></li>\r\n");
      out.write("							<li class=\"ftco-animate\"><a href=\"#\"><span\r\n");
      out.write("									class=\"icon-instagram\"></span></a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md\">\r\n");
      out.write("					<div class=\"ftco-footer-widget mb-4 ml-md-5\">\r\n");
      out.write("						<h2 class=\"ftco-heading-2\">Information</h2>\r\n");
      out.write("						<ul class=\"list-unstyled\">\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">About</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Services</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Term and Conditions</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Best Price\r\n");
      out.write("									Guarantee</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Privacy &amp;\r\n");
      out.write("									Cookies Policy</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md\">\r\n");
      out.write("					<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("						<h2 class=\"ftco-heading-2\">Customer Support</h2>\r\n");
      out.write("						<ul class=\"list-unstyled\">\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">FAQ</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Payment Option</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Booking Tips</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">How it works</a></li>\r\n");
      out.write("							<li><a href=\"#\" class=\"py-2 d-block\">Contact Us</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md\">\r\n");
      out.write("					<div class=\"ftco-footer-widget mb-4\">\r\n");
      out.write("						<h2 class=\"ftco-heading-2\">Have a Questions?</h2>\r\n");
      out.write("						<div class=\"block-23 mb-3\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><span class=\"icon icon-map-marker\"></span><span\r\n");
      out.write("									class=\"text\">제주 제주시 다호5길 400 제주도로WE</span></li>\r\n");
      out.write("								<li><a href=\"#\"><span class=\"icon icon-phone\"></span><span\r\n");
      out.write("										class=\"text\">+81) 016-7117-972</span></a></li>\r\n");
      out.write("								<li><a href=\"#\"><span class=\"icon icon-envelope\"></span><span\r\n");
      out.write("										class=\"text\">info@human.com</span></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-12 text-center\">\r\n");
      out.write("\r\n");
      out.write("					<p>\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("						Copyright &copy;\r\n");
      out.write("						<script>\r\n");
      out.write("							document.write(new Date().getFullYear());\r\n");
      out.write("						</script>\r\n");
      out.write("						All rights reserved | This template is made with <i\r\n");
      out.write("							class=\"icon-heart color-danger\" aria-hidden=\"true\"></i> by <a\r\n");
      out.write("							href=\"https://colorlib.com\" target=\"_blank\">Colorlib</a>\r\n");
      out.write("						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("					</p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- loader -->\r\n");
      out.write("	<div id=\"ftco-loader\" class=\"show fullscreen\">\r\n");
      out.write("		<svg class=\"circular\" width=\"48px\" height=\"48px\">\r\n");
      out.write("			<circle class=\"path-bg\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				stroke-width=\"4\" stroke=\"#eeeeee\" />\r\n");
      out.write("			<circle class=\"path\" cx=\"24\" cy=\"24\" r=\"22\" fill=\"none\"\r\n");
      out.write("				stroke-width=\"4\" stroke-miterlimit=\"10\" stroke=\"#F96D00\" /></svg>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery-migrate-3.0.1.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/popper.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.stellar.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/aos.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.animateNumber.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/bootstrap-datepicker.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/jquery.timepicker.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/scrollax.min.js\"></script>\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/google-map.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("   \r\n");
      out.write("   var sumpay = document.getElementById(\"sumpay\");\r\n");
      out.write("   var rentdateflag = 0;\r\n");
      out.write("   \r\n");
      out.write("   function cal(){      \r\n");
      out.write("      var carname = document.getElementById(\"carlist\");\r\n");
      out.write("      var rentdate = document.getElementById(\"rentdate\");\r\n");
      out.write("      var returndate = document.getElementById(\"returndate\");\r\n");
      out.write("      var coupon = document.getElementById(\"coupon\");\r\n");
      out.write("      var insurance = document.querySelector('input[name=\"insurance\"]:checked');\r\n");
      out.write("         \r\n");
      out.write("      $.ajax({\r\n");
      out.write("         url:'./paySet',\r\n");
      out.write("         data:{'carname':carname.value, 'rentdate':rentdate.value, 'returndate':returndate.value, 'coupon':coupon.value, 'insurance':insurance.value}, \r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("         type:'GET',\r\n");
      out.write("         cache:false,   // cache옵션값을 false로 주게 되면 브라우저 캐쉬를 막아서 캐쉬된 값이 아닌 현재 값을 호출해 올 수 있다.\r\n");
      out.write("         success: function(data){\r\n");
      out.write("            if(data!=\"\"){\r\n");
      out.write("               sumpay.innerHTML = \"총 금액\"+data+\"원입니다.\";\r\n");
      out.write("               \r\n");
      out.write("            } else if(data==\"\") {\r\n");
      out.write("              \r\n");
      out.write("            }      \r\n");
      out.write("         }, error : function(){\r\n");
      out.write("            console.log(\"-----실패-------\"+coupon.value);\r\n");
      out.write("         }\r\n");
      out.write("         \r\n");
      out.write("      });\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   function car(e) {\r\n");
      out.write("	   var sDt = document.getElementById('rentdate');\r\n");
      out.write("		var eFdt = document.getElementById('returndate');\r\n");
      out.write("		sDt.value=\"연도-월-일\";\r\n");
      out.write("       	eFdt.value=\"연도-월-일\";\r\n");
      out.write("        var carlist_a = [ \"스파크\", \"케스퍼\", \"레이\", \"모닝\" ];\r\n");
      out.write("        var carlist_b = [ \"아반떼 AD\", \"아이오닉\", \"벨로스터\", \"K3\", \"K3 GT\" ];\r\n");
      out.write("        var carlist_c = [ \"쏘나타\", \"G70\", \"K5\", \"스팅어 2.5\", \"LF 쏘나타\", \"BMW X5\" ];\r\n");
      out.write("        var carlist_d = [ \"그랜저2.5\", \"그랜저3.3\", \"K7\", \"K8\" ];\r\n");
      out.write("        var carlist_e = [ \"제네시스 G80\", \"G90\", \"G90 리무진 \", \"벤츠 E클래스\",\"아우디 A6\" ];\r\n");
      out.write("        var carlist_f = [ \"스타리아\", \"스타렉스\", \"카니발\", \"카니발 KA4\" ];\r\n");
      out.write("        var carlist_g = [ \"포드\", \"랜드로버\", \"GV80\", \"GV70\", \"싼타페\", \"투싼\", \"베뉴\" ];\r\n");
      out.write("        var carlist_h = [ \"볼트\", \"코나\", \"GV70\", \"GV60\", \"테슬라3\", \"EV6\" ];\r\n");
      out.write("        var target = document.getElementById(\"carlist\");\r\n");
      out.write("        if (e.value == \"경차\") {\r\n");
      out.write("           var d = carlist_a;\r\n");
      out.write("        } else if (e.value == \"소형차\") {\r\n");
      out.write("           var d = carlist_b;\r\n");
      out.write("        } else if (e.value == \"중형차\") {\r\n");
      out.write("           var d = carlist_c;\r\n");
      out.write("        } else if (e.value == \"준대형차\") {\r\n");
      out.write("           var d = carlist_d;\r\n");
      out.write("        } else if (e.value == \"대형차\") {\r\n");
      out.write("           var d = carlist_e;\r\n");
      out.write("        } else if (e.value == \"승합차\") {\r\n");
      out.write("           var d = carlist_f;\r\n");
      out.write("        } else if (e.value == \"SUV\") {\r\n");
      out.write("           var d = carlist_g;\r\n");
      out.write("        } else if (e.value == \"전기차\") {\r\n");
      out.write("           var d = carlist_h;\r\n");
      out.write("        }\r\n");
      out.write("        target.options.length = 0;\r\n");
      out.write("        for (x in d) {\r\n");
      out.write("           var opt = document.createElement(\"option\");\r\n");
      out.write("           opt.value = d[x];\r\n");
      out.write("           opt.innerHTML = d[x];\r\n");
      out.write("           target.appendChild(opt);\r\n");
      out.write("        }\r\n");
      out.write("     }\r\n");
      out.write("   var carlist = document.getElementById(\"carlist\");\r\n");
      out.write("	carlist.onchange=()=>{\r\n");
      out.write("		var sDt = document.getElementById('rentdate');\r\n");
      out.write("		var eFdt = document.getElementById('returndate');\r\n");
      out.write("		sDt.value=\"연도-월-일\";\r\n");
      out.write("       eFdt.value=\"연도-월-일\";\r\n");
      out.write("	}\r\n");
      out.write("   document.getElementById('rentdate').onchange=() => {\r\n");
      out.write("         var sDt = document.getElementById('rentdate').value;\r\n");
      out.write("         var eFdt = document.getElementById('returndate');\r\n");
      out.write("         eFdt.value=\"연도-월-일\";\r\n");
      out.write("          //var sTm = $(\"#time\").val();\r\n");
      out.write("          \r\n");
      out.write("         // var sum = sDt+\" \"+sTm+\":00:00\";\r\n");
      out.write("\r\n");
      out.write("          var sDate = new Date(sDt);\r\n");
      out.write("        var now = new Date();\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("         if(sDate<now) {\r\n");
      out.write("            rentdateflag=0;\r\n");
      out.write("            alert(\"지난 시간으로 예약 할 수 없습니다.\");\r\n");
      out.write("            var eSdt = document.getElementById('rentdate');\r\n");
      out.write("            eSdt.value=\"연도-월-일\";\r\n");
      out.write("         } else {\r\n");
      out.write("            rentdateflag++;\r\n");
      out.write("            return true;\r\n");
      out.write("         }\r\n");
      out.write("     }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   document.getElementById('returndate').onchange=() => {\r\n");
      out.write("      var eFdt = document.getElementById('returndate');\r\n");
      out.write("      if(rentdateflag==0){\r\n");
      out.write("            alert(\"대여일을 선택 해주세요.\");\r\n");
      out.write("            eFdt.value=\"연도-월-일\";\r\n");
      out.write("            return;\r\n");
      out.write("         }\r\n");
      out.write("       var sDt = document.getElementById('rentdate').value;\r\n");
      out.write("          var fDt = document.getElementById('returndate').value;\r\n");
      out.write("          var sTm = $(\"#time\").val();   \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("         var sDate = new Date(sDt);\r\n");
      out.write("          \r\n");
      out.write("          var fDate = new Date(fDt);\r\n");
      out.write("        var now = new Date();\r\n");
      out.write("          \r\n");
      out.write("         if(fDt <= sDt){\r\n");
      out.write("            alert(\"반납일은 대여일 이후로 해주세요.\");\r\n");
      out.write("            //var eFdt = document.getElementById('returndate');\r\n");
      out.write("            eFdt.value=\"연도-월-일\";\r\n");
      out.write("         } else if((fDate-now)< 0) {\r\n");
      out.write("            alert(\"지난 시간으로 예약 할 수 없습니다.\");\r\n");
      out.write("            //var eFdt = document.getElementById('returndate');\r\n");
      out.write("            eFdt.value=\"연도-월-일\";\r\n");
      out.write("         } else {            \r\n");
      out.write("            chkdate(sDate,fDate);\r\n");
      out.write("         }\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   function chkdate(sDate,fDate) {  //sumSdt은 시작일, fDt는 종료일이다.\r\n");
      out.write("      var carname=document.getElementById('carlist');\r\n");
      out.write("      var res_day = [];\r\n");
      out.write("      var reservNo = null;\r\n");
      out.write("     \r\n");
      out.write("        while(sDate.getTime() <= fDate.getTime()){\r\n");
      out.write("              var _mon_ = (sDate.getMonth()+1);\r\n");
      out.write("              _mon_ = _mon_ < 10 ? '0'+_mon_ : _mon_;\r\n");
      out.write("              var _day_ = sDate.getDate();\r\n");
      out.write("              _day_ = _day_ < 10 ? '0'+_day_ : _day_;              \r\n");
      out.write("               res_day.push(sDate.getFullYear() + '-' + _mon_ + '-' +  _day_);\r\n");
      out.write("               sDate.setDate(sDate.getDate() + 1);\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("        for(var i=0; i<res_day.length; i++){\r\n");
      out.write("           \r\n");
      out.write("           $.ajax({\r\n");
      out.write("              url:'");
      out.print(request.getContextPath());
      out.write("/chkDate?rentdate='+res_day[i]+'&carname='+carname.value,\r\n");
      out.write("              type:'GET',\r\n");
      out.write("              async:false,  // 동기식 처리 > 함수가 순차적으로 실행되기 위해서\r\n");
      out.write("              cache:false,\r\n");
      out.write("              success:function(data){\r\n");
      out.write("                 if(data==\"\"){   // 예약 가능할 때, 넘어오는 데이터 null\r\n");
      out.write("                    var fDt = document.getElementById('returndate');\r\n");
      out.write("                    fDt.value=res_day[i];\r\n");
      out.write("	                 } else if(data!=\"\"){  // 기존에 예약 있을 때, 넘어오는 데이터 존재\r\n");
      out.write("                    reservNo += (res_day[i]+\", \");\r\n");
      out.write("                    var sDt = document.getElementById('rentdate');\r\n");
      out.write("                    var fDt = document.getElementById('returndate');\r\n");
      out.write("                    fDt.value=\"연도-월-일\";\r\n");
      out.write("                    sDt.value=\"연도-월-일\";\r\n");
      out.write("                 }\r\n");
      out.write("              }, error : function(){\r\n");
      out.write("               console.log(\"-----실패-------\");\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("           })\r\n");
      out.write("        }\r\n");
      out.write("        if(reservNo!=null){\r\n");
      out.write("           reservNo=reservNo.replace(\"null\",\"\");\r\n");
      out.write("           alert(\"해당 차량은 이미 \"+reservNo+\"날에 예약이 있습니다. \\n 다른 날짜를 선택해주세요\");\r\n");
      out.write("        } else {\r\n");
      out.write("           alert(\"예약 가능한 날짜입니다.\");\r\n");
      out.write("		   cal();\r\n");
      out.write("        }\r\n");
      out.write("   }\r\n");
      out.write("   keyevent = () => {\r\n");
      out.write("      licensenum.value = autoHypenlicensenum(licensenum.value);\r\n");
      out.write("   }\r\n");
      out.write("   function autoHypenlicensenum(str){      //00-00-000000-00\r\n");
      out.write("         str = str.replace(/[^0-9]/g,'');\r\n");
      out.write("         var tmp = '';\r\n");
      out.write("         if(str.length < 3){\r\n");
      out.write("           return str;\r\n");
      out.write("         }else if(str.length < 5){\r\n");
      out.write("           tmp += str.substr(0, 2);\r\n");
      out.write("           tmp += '-';\r\n");
      out.write("           tmp += str.substr(2);\r\n");
      out.write("           return tmp;\r\n");
      out.write("         }else if(str.length < 11){\r\n");
      out.write("           tmp += str.substr(0, 2);\r\n");
      out.write("           tmp += '-';\r\n");
      out.write("           tmp += str.substr(2, 2);\r\n");
      out.write("           tmp += '-';\r\n");
      out.write("           tmp += str.substr(4, 6);\r\n");
      out.write("           return tmp;\r\n");
      out.write("         }else{\r\n");
      out.write("           tmp += str.substr(0, 2);\r\n");
      out.write("           tmp += '-';\r\n");
      out.write("           tmp += str.substr(2, 2);\r\n");
      out.write("           tmp += '-';\r\n");
      out.write("           tmp += str.substr(4, 6);\r\n");
      out.write("           tmp += '-';\r\n");
      out.write("           tmp += str.substr(10, 2);\r\n");
      out.write("           return tmp;\r\n");
      out.write("         }\r\n");
      out.write("         return str;\r\n");
      out.write("       }\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<a data-toggle=\"modal\" href=\"#myModal\" class=\"nav-link\">로그인</a>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/reserve/reserve.jsp(148,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.cartype.length()>=2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("										<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.cartype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" selected hidden=\"\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.cartype}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("										");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("										");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/views/reserve/reserve.jsp(159,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.carname eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("											<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.carname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" selected hidden>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cvo.carname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/reserve/reserve.jsp(199,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time_pick < 12}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            			오전 ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time_pick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("시\r\n");
          out.write("                          				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/reserve/reserve.jsp(202,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time_pick == 12}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                              			오후 ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time_pick}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("시\r\n");
          out.write("                           				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/reserve/reserve.jsp(205,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time_pick > 12}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                              			오후 ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time_pick-12}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("시\r\n");
          out.write("                           				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/reserve/reserve.jsp(223,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/reserve/reserve.jsp(223,9) '${coupon }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${coupon }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/reserve/reserve.jsp(223,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("mvo");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("										<option>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${coupon }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("									");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
